### ISSUE TITLE
Issue with the 'class' prefix

### ISSUE THREAD

**Issue by tieskuiper** [ways-agency/shopify-liquid-snippets#19]
I am experiencing an issue with the autocomplete functionality in the Shopify Liquid extension (or possibly the official Shopify Liquid extension). Specifically, when I type “class” within a div tag, the autocomplete suggestion does not include the expected ="". Instead, it outputs just the word “class” without the equal sign and quotation marks.

Additionally, I notice that I receive two autocomplete suggestions when typing “class”. However, only the second suggestion is correct and includes the proper ="" format.

Has anyone else encountered this issue, and if so, is there a known solution?

![Screen Recording 2024-05-17 at 11 40 49](https://github.com/ways-agency/shopify-liquid-snippets/assets/127101126/ac995260-1131-424a-9899-f5c8ffe5702c)

**Comment by stijns96** [comment]
Hi @tieskuiper,

I'm sorry for the very late response... Haven't seen this one. This was due to the extension from Shopify themselves. They added support for HTML, but it didn't add the `=""` behind the attributes that needs it.

They now fixed this in v2.6.0. I'm planning a release.

The second `class` that you see in the list was coming from my extension. That one worked correctly. But whenever I released my version, the second one should be gone.
